# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 02:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171125_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ManyToManyField(related_name='post', to='blog.Profile'),
        ),
    ]
