# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-26 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171125_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ManyToManyField(related_name='comments', to='blog.Profile'),
        ),
    ]
