# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-27 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20171125_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='Downvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ManyToManyField(related_name='downvote', to='blog.Post')),
                ('user', models.ManyToManyField(related_name='downvote', to='blog.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Upvote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ManyToManyField(related_name='upvote', to='blog.Post')),
                ('user', models.ManyToManyField(related_name='upvote', to='blog.Profile')),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ManyToManyField(related_name='comments', to='blog.Post'),
        ),
    ]
