# Generated by Django 2.1.3 on 2018-11-26 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20171126_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='Title your post  ', max_length=50),
        ),
    ]
